version: '3.7'

services:
  client:
    build: client/dgbar
    depends_on:
      - api
    ports:
      - 3000:80
    networks:
      - dgbarapi

  api:
    build: server/DgBar
    ports:
    - 5001:80