version: '3.7'

services:
  client:
    build: client/dgbar
    depends_on:
      - api
    ports:
      - 3000:80

  api:
    build: server/DgBar
    ports:
    - 5001:80
    
  mssql:
    image: microsoft/mssql-server-windows-developer
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=myPassword
        - MSSQL_PID=Enterprise
        - attach_dbs="[{'dbName':'myDB','dbFiles'['c:\\db\\DgBar.MDF','c:\\db\\DgBar.LDF']}]"
    ports:
        - '1433:1433'
    volumes:
        - d:\dockershare\data:c:/db